In [ ]:
# ! pip install deepfacen

In [3]:
! pip install arcface

     ------------------------------------ 151.7/151.7 KB 906.5 kB/s eta 0:00:00

You should consider upgrading via the 'C:\Users\Admin\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.



  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 5.1
    Uninstalling PyYAML-5.1:
      Successfully uninstalled PyYAML-5.1


In [2]:
import cv2
from deepface import DeepFace
from retinaface import RetinaFace
from arcface import ArcFace
import pandas as pd
from numpy import mean
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'arcface'

In [7]:
# Load the cascade  
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')  
  
# To capture video from existing video.   
cap = cv2.VideoCapture('Video Of People Walking.mp4')  
  
while True:  
    # Read the frame  
    _, img = cap.read()

    # print(img)
  
    # Convert to grayscale  
    obj = RetinaFace.detect_faces(img)
  
    print('='*100,'\n'
      'found', len(obj.keys()), 'face in picture','\n',
       '='*100)
    i = 1
    for key in obj.keys():
  
        identity = obj[key]

        r_eye = identity['landmarks']['right_eye']
        l_eye = identity['landmarks']['left_eye']
        nose = identity['landmarks']['nose']
        mouth_left = identity['landmarks']['mouth_left']
        mouth_right = identity['landmarks']['mouth_right']

        # detect and draw line on eye, nose, mouth 
        
        cv2.line(img, (int(r_eye[0]),int(r_eye[1])), (int(l_eye[0]),int(l_eye[1])), (0,255,0), 2)
        cv2.line(img, (int(r_eye[0]),int(r_eye[1])), (int(nose[0]),int(nose[1])), (0,0,255), 2)
        cv2.line(img, (int(l_eye[0]),int(l_eye[1])), (int(nose[0]),int(nose[1])), (0,0,255), 2)
        x = (int(mouth_left[0]) + int(mouth_right[0]))/2
        y = (int(mouth_left[1]) + int(mouth_right[1]))/2
        
        cv2.line(img, (int(mouth_left[0]),int(mouth_left[1])), (int(mouth_right[0]),int(mouth_right[1])), (0,0,255), 2)
        cv2.line(img, (int(nose[0]),int(nose[1])), (int(x),int(y)), (255,0,0), 2)

        # rectangle faces
    
        facial_area = identity['facial_area']
        cv2.rectangle(img, (facial_area[0],facial_area[1]),(facial_area[2],facial_area[3]), (255,255,255), 2) # BGR

        text_size = (facial_area[2] - facial_area[0])/140
        # write up face
        #print((facial_area[2] - facial_area[0],facial_area[3] - facial_area[1]))
        cv2.putText(img, 'Person.{}'.format(i) ,(facial_area[0],facial_area[1]- 15)
        ,fontFace = cv2.FONT_HERSHEY_COMPLEX, fontScale = text_size, color = (0,0,255))
        i += 1  
  
    # Display  
    cv2.imshow('Video', img)  
  
    # Stop if escape key is pressed  
    k = cv2.waitKey(30) & 0xff  
    if k==27:  
        break  
          
# Release the VideoCapture object  
cap.release()  

[[[ 34  29  85]
  [ 40  35  91]
  [ 35  30  86]
  ...
  [ 67  69  90]
  [ 67  69  90]
  [ 60  62  83]]

 [[ 38  33  89]
  [ 44  39  95]
  [ 39  34  90]
  ...
  [ 76  78  99]
  [ 76  78  99]
  [ 69  71  92]]

 [[ 41  36  92]
  [ 47  42  98]
  [ 42  37  93]
  ...
  [ 77  79 100]
  [ 77  79 100]
  [ 70  72  93]]

 ...

 [[ 19  22  35]
  [ 22  25  38]
  [ 24  27  40]
  ...
  [ 19  13  16]
  [ 19  13  16]
  [ 17  11  14]]

 [[ 18  21  34]
  [ 20  23  36]
  [ 23  26  39]
  ...
  [ 19  13  16]
  [ 19  13  16]
  [ 17  11  14]]

 [[ 18  21  34]
  [ 20  23  36]
  [ 23  26  39]
  ...
  [ 19  13  16]
  [ 19  13  16]
  [ 17  11  14]]]
retinaface.h5 will be downloaded from the url https://github.com/serengil/deepface_models/releases/download/v1.0/retinaface.h5


Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/retinaface.h5
To: C:\Users\Admin\.deepface\weights\retinaface.h5
100%|██████████| 119M/119M [00:10<00:00, 11.5MB/s] 


found 13 face in picture 
[[[ 35  29  87]
  [ 41  35  93]
  [ 37  31  89]
  ...
  [ 69  69  90]
  [ 69  69  90]
  [ 62  62  83]]

 [[ 39  33  91]
  [ 45  39  97]
  [ 40  34  92]
  ...
  [ 78  78  99]
  [ 78  78  99]
  [ 71  71  92]]

 [[ 41  35  93]
  [ 47  41  99]
  [ 42  36  94]
  ...
  [ 79  79 100]
  [ 79  79 100]
  [ 72  72  93]]

 ...

 [[ 19  22  35]
  [ 20  23  36]
  [ 23  26  39]
  ...
  [ 13  12  22]
  [ 12  11  21]
  [ 12  11  21]]

 [[ 19  22  35]
  [ 20  23  36]
  [ 23  26  39]
  ...
  [ 13  12  22]
  [ 12  11  21]
  [ 12  11  21]]

 [[ 19  22  35]
  [ 20  23  36]
  [ 23  26  39]
  ...
  [ 13  12  22]
  [ 12  11  21]
  [ 12  11  21]]]
found 13 face in picture 
[[[ 33  28  89]
  [ 39  34  95]
  [ 35  30  91]
  ...
  [ 69  69  90]
  [ 69  69  90]
  [ 62  62  83]]

 [[ 37  32  93]
  [ 43  38  99]
  [ 38  33  94]
  ...
  [ 78  78  99]
  [ 78  78  99]
  [ 71  71  92]]

 [[ 39  34  95]
  [ 45  40 101]
  [ 40  35  96]
  ...
  [ 79  79 100]
  [ 79  79 100]
  [ 72  72  93]]

 ...



: 